analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.5109612
  brandStrength: 0.4688027
  lightness: 0.9038786
  brandColors:
    - '#040406'
    - '#5C5B5D'
    - '#F2F2F2'
    - '#919191'
  rhythmicContrast: 0.386172
typography_spectrum: 0.2082671928219497
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 1
favicon: null
name: Guardian Information Services
